### ISSUE TITLE
Broken english

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/rails-api-one-to-many#6]
Often, the resources of our application will have a relationship with each other. In our three domains, authors have many books, doctors have many patients, and recipes have many ingredients.
SHOULD BE:
Often, the resources of our application will relationships with each other. In our three domains, authors have many books, doctors have many patients, and recipes have many ingredients.

**Comment by gaand** [comment]
@payne-chris-r: Did you put the corrected text above the`SHOULD BE:` line?

**Comment by jrhorn424** [comment]
> @payne-chris-r: Did you put the corrected text above theSHOULD BE: line?

I know you didn't ask me, but it appears that way to me.

**Comment by payne-chris-r** [comment]
Yes. #facepalm.

**Comment by payne-chris-r** [comment]
IS:
Often, the resources of our application will relationships with each other. In our three domains, authors have many books, doctors have many patients, and recipes have many ingredients.

SHOULD BE:
Often, the resources of our application will have relationships with each other. In our three domains, authors have many books, doctors have many patients, and recipes have many ingredients.

**Comment by payne-chris-r** [comment]
Thanks @gaand and @jrhorn424
